server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vuemanager?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: "040925"
  security:
    user:
      name: root
      password: admin
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

jwt:
  expire: 604800
  secret: f4e2e52071b2517d36b54741c0ade5d3
  header: Authorization
