server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vuemanager?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: "040925"
  security:
    user:
      name: root
      password: admin
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

jwt:
  expire: 7200
  secret: fi8n3439n439n43ld9ne9343fdfet49h
  header: Authorization
